# Build context: generated by npm run prepare:server in .cloud-run.
FROM node:20-slim AS build
WORKDIR /workspace/app
COPY package.json package-lock.json ./
RUN npm ci
COPY app/server ./server
COPY home-teacher-common ../home-teacher-common
RUN npm run build
RUN npm prune --omit=dev

FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
COPY --from=build /workspace/app/package.json ./
COPY --from=build /workspace/app/node_modules ./node_modules
COPY --from=build /workspace/app/dist/server.mjs ./server/index.mjs
USER node
EXPOSE 8080
CMD ["node", "server/index.mjs"]
